
ORACLE = "ORACLE"
MYSQL = "MYSQL"
SQLSERVER = "SQLSERVER"
POSTGRESQL = "POSTGRESQL"

dialect_driver = {
    ORACLE: "oracle+cx_oracle",
    MYSQL: "mysql",
    SQLSERVER: "mssql+pymssql",
    POSTGRESQL: "postgresql+psycopg2"
}

# Sample Table Name
INSERT_TEST = "INSERT_TEST"
UPDATE_TEST = "UPDATE_TEST"
DELETE_TEST = "DELETE_TEST"
STRING_TEST = "STRING_TEST"
NUMERIC_TEST = "NUMERIC_TEST"
DATETIME_TEST = "DATETIME_TEST"
BINARY_TEST = "BINARY_TEST"
LOB_TEST = "LOB_TEST"
ORACLE_TEST = "ORACLE_TEST"
SQLSERVER_TEST = "SQLSERVER_TEST"

SOURCE = "SOURCE"
TARGET = "TARGET"
BOTH = "BOTH"

# Oracle Data Types
ORACLE_CHAR = "CHAR"
ORACLE_NCHAR = "NCHAR"
ORACLE_VARCHAR2 = "VARCHAR2"
ORACLE_NVARCHAR2 = "NVARCHAR2"
ORACLE_LONG = "LONG"
ORACLE_NUMBER = "NUMBER"
ORACLE_BINARY_FLOAT = "BINARY_FLOAT"
ORACLE_BINARY_DOUBLE = "BINARY_DOUBLE"
ORACLE_FLOAT = "FLOAT"
ORACLE_DATE = "DATE"
ORACLE_TIMESTAMP = "TIMESTAMP"
ORACLE_INTERVAL = "INTERVAL"
ORACLE_RAW = "RAW"
ORACLE_LONG_RAW = "LONG RAW"
ORACLE_CLOB = "CLOB"
ORACLE_NCLOB = "NCLOB"
ORACLE_BLOB = "BLOB"
ORACLE_ROWID = "ROWID"
