
SETTINGS:
  # ERROR | INFO | DEBUG ( Default. ERROR )
  LOG_LEVEL: info

  # NONE | SQL | ALL ( Default. NONE )
  SQL_LOGGING: all

  # ( Default. AMERICAN_AMERICA.AL32UTF8 )
  NLS_LANG:

  # Array binding max size ( Default. 5000 )
  DML_ARRAY_SIZE:


DATABASES:
  SOURCE:
    # ORACLE | MYSQL | SQLSERVER | POSTGRESQL | CUBRID | TIBERO
    DBMS: oracle

    # Database server IP
    HOST: 192.168.56.90

    # Database connection port
    PORT: 1521

    # Database name or Instance name
    DBNAME: ORA19a

    # Connect user id.
    USERNAME: cdctest

    # Connect user password.
    PASSWORD: cdctest

    # Schema Name. if dbms_type is Oracle, MySQL, CUBRID or TIBERO, need no value
    SCHEMA:

  TARGET:
    DBMS:
    HOST:
    PORT:
    DBNAME:
    USERNAME:
    PASSWORD:


INITIAL_DATA:
  UPDATE_TEST:
    # Initial number of data in UPDATE_TEST Table ( Condition. N >= 1, Default. 30000 )
    RECORD_COUNT:
    # Commit unit of UPDATE_TEST Table ( Condition. N >= 1, Default. 2000 )
    COMMIT_COUNT:

  DELETE_TEST:
    RECORD_COUNT:
    COMMIT_UNIT:
