
ORACLE = "ORACLE"
MYSQL = "MYSQL"
MARIADB = "MARIADB"
SQLSERVER = "SQLSERVER"
POSTGRESQL = "POSTGRESQL"
CUBRID = "CUBRID"
TIBERO = "TIBERO"
# cb (CB): cdcbench
cb_support_dbms = [ORACLE, MYSQL, MARIADB, SQLSERVER, POSTGRESQL, CUBRID, TIBERO]
# sa (SA): SQLAlchemy
sa_unsupported_dbms = [CUBRID, TIBERO]

# Sample Table Name
INSERT_TEST = "INSERT_TEST"
UPDATE_TEST = "UPDATE_TEST"
DELETE_TEST = "DELETE_TEST"
STRING_TEST = "STRING_TEST"
NUMERIC_TEST = "NUMERIC_TEST"
DATETIME_TEST = "DATETIME_TEST"
BINARY_TEST = "BINARY_TEST"
LOB_TEST = "LOB_TEST"
ORACLE_TEST = "ORACLE_TEST"
SQLSERVER_TEST = "SQLSERVER_TEST"
sample_tables = [
    INSERT_TEST, UPDATE_TEST, DELETE_TEST,
    STRING_TEST, NUMERIC_TEST, DATETIME_TEST, BINARY_TEST, LOB_TEST,
    ORACLE_TEST, SQLSERVER_TEST
]

DEFAULT_CONFIG_FILE_NAME = "default.yaml"

PRIMARY_KEY = "PRIMARY KEY"
PRIMARY_KEY_BAR = "PRIMARY-KEY"
UNIQUE = "UNIQUE"
NON_KEY = "NON KEY"
NON_KEY_BAR = "NON-KEY"

# End message
COMPLETE = "Complete"
COMMIT = "Commit"
ROLLBACK = "Rollback"
FAIL = "Fail"

INSERT = "INSERT"
UPDATE = "UPDATE"
DELETE = "DELETE"

# Logger name
CDCBENCH = "cdcbench"
SQL = "sql"
