@echo off
SETLOCAL enabledelayedexpansion
SET INSERT_ROW=400000
SET COMMIT_UNIT=100
SET UPDATE_START_NUM=1
SET UPDATE_END_NUM=15
SET DELETE_START_NUM=1
SET DELETE_END_NUM=15

python cdcbench.py -i !INSERT_ROW! !COMMIT_UNIT!
python cdcbench.py -u !UPDATE_START_NUM! !UPDATE_END_NUM!
python cdcbench.py -d !DELETE_START_NUM! !DELETE_END_NUM!